services:
  web:
    # serve the nginx alpine image
    image: nginx:alpine
    # expose the port 80
    ports:
      - "8001:80"
    # mount the local directory to the container
    volumes:
      - ./web:/usr/share/nginx/html
    # restart the container if it fails
    restart: unless-stopped
  